### ISSUE TITLE
Level 4 tiny ult instantly crashes game

### ISSUE THREAD

**Issue by chrisinajar** [AngelArenaAllstars/oaa#126]
it probably shouldn't

**Comment by Chronophylos** [comment]
I think the problem is that the game looks for a new Level 4 model for Tiny.
We could:
* not look for a new model
* use the same Level 3 model
* use new custom models for the missing Level 4+

**Comment by spar36** [comment]
I think we should get this resolved, atleast for sunday just to keep a bunch of games from crashing.
1) create a new lvl 4 model
2) use old model from lvl 3 / not look for a new model.
or
3) take tiny out of the game, just for sunday.
