### ISSUE TITLE
Duels

### ISSUE THREAD

**Issue by chrisinajar** [AngelArenaAllstars/oaa#2]
Duels are the staple of Angel Arena. Implement them!

* HUD element showing the remaining duel timer
  * **extra credit** for adding a vote widget to force duel
* When timer hits 0, DUEL!
  * Teleport `n of m` heroes into the arena, teleport the remainder to the sidelines
  * Disable all sidelines heroes
  * Reset the cooldowns and resources of all heroes, storing their previous values
* When only 1 team has heroes left, the duel is over
  * Teleport all heroes back to where they were before the duel
  * Restore all resources and cooldowns (optionally minus time spent in duel) to what they were

**Comment by darklordabc** [comment]
I highly recommend using the code of other games that have implemented a duel mechanic. Angel arena guy is fine with people using the code, and I've also implemented duels into Redux. You will save yourself a lot of time and heartache just using other mod's already implemented solutions.

**Comment by chrisinajar** [comment]
have any links? sample code is always appreciated. it'd be great to create
a generic save-state API to make coding things like this trivial.
