### ISSUE TITLE
Creep camps

### ISSUE THREAD

**Issue by chrisinajar** [AngelArenaAllstars/oaa#4]
Currently there is a dead simple creep camp system which supports the following:

* Create areas with a special `creep_camp` name.
* All `creep_camp`s have a type and a maximum number of units allowed to spawn

### New Features

* [x] **Creeps Upgrade In Place**
We want to add a special functionality when the camp is at maximum size: Upgrade the existing creeps instead of spawning new ones or not spawning anything. This upgrade path should likely be linear based on the core creeps (not the upgraded ones) or it should be plainly diminishing.

* [x] **Creeps Upgrade Over Time**
As the game goes, all of the creeps spawning everywhere should progressively get stronger and stronger. This should be as configurable and generic as possible as it is likely we'll reuse this logic a lot.

 * [x] **Creeps Drop Items**
Right now they don't! Figure out a good creep item drop system and expect it to need to be changed a million times over again and again by the balance team. The droppable items should also upgrade along similar tracks as the above two features.

**Comment by Rachol** [comment]
Hi, I am going to implement these new features within next 7 days.

**Comment by Rachol** [comment]
I will commit the item drop system within next 24 hours, sorry for the delay

**Comment by Rachol** [comment]
Ready, after my pull request goes through... This is pretty much done
