### ISSUE TITLE
Create/edit Hero Units (Like Misha)

### ISSUE THREAD

**Issue by warpdragon** [AngelArenaAllstars/oaa#89]
The Items are on their way, and the heroes... but we need someone to go in to NPC Data (KeyValues) and alter some of the existing units and also to create some new units which are to comport with the values contained in the O-fficial hero Balance Document. There will be a party with c🍰ke once you've completed your task. 

Such units include, but aren't necessarily limited to:
Misha
Boar
Hawk
Earth
Storm
Fire
Spiderlings
Treants (we also need a new custom treant in addition to the existing ones)
Courier (don't alter it, we just need a new one for decoy courier).

**Comment by warpdragon** [comment]
Also for some reason Warlock ultimate at highest lvl makes the explodey part, but Bob is afk

**Comment by Honeth** [comment]
Warp and i have been working on this
 https://docs.google.com/spreadsheets/d/15csYDGxt0-Px_BCRfIM2ADhwtemTG2mvvERfzpD5__w/edit#gid=0

Is what warp made to track progress, i just need several value's to be generated / created for several units.
